package org.walker.spring.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.walker.spring.web.model.RolePermission;
import org.walker.spring.web.model.RolePermissionExample;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Oct 20 17:57:38 CST 2020
     */
    long countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Oct 20 17:57:38 CST 2020
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Oct 20 17:57:38 CST 2020
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Oct 20 17:57:38 CST 2020
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Oct 20 17:57:38 CST 2020
     */
    List<RolePermission> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Oct 20 17:57:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Tue Oct 20 17:57:38 CST 2020
     */
    int updateByExample(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);
}