package org.walker.spring.web.model;

public class RolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.RoleID
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.PermissionID
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    private Integer permissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.RoleID
     *
     * @return the value of role_permission.RoleID
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.RoleID
     *
     * @param roleid the value for role_permission.RoleID
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.PermissionID
     *
     * @return the value of role_permission.PermissionID
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    public Integer getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.PermissionID
     *
     * @param permissionid the value for role_permission.PermissionID
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    public void setPermissionid(Integer permissionid) {
        this.permissionid = permissionid;
    }
}