package org.walker.spring.web.model;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ID
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.RoleName
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ID
     *
     * @return the value of role.ID
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ID
     *
     * @param id the value for role.ID
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.RoleName
     *
     * @return the value of role.RoleName
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.RoleName
     *
     * @param rolename the value for role.RoleName
     *
     * @mbg.generated Tue Oct 20 17:54:20 CST 2020
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
}