spring:
  profiles:
    active: dev
  batch:
    job:
      enabled: false
server:
  port: 8009
  servlet:
    context-path: /api
---
spring:
  profiles: dev
---
spring:
  profiles: uat
---
spring:
  profiles: prod